# Generated by Django 3.1.6 on 2021-02-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip_address', models.CharField(max_length=39)),
                ('dest_ip_address', models.CharField(max_length=39)),
                ('port', models.CharField(max_length=5)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
