# Generated by Django 3.1.6 on 2021-02-24 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packet',
            options={'managed': True},
        ),
    ]
