# Generated by Django 3.1.7 on 2021-03-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packet',
            name='fin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packet',
            name='psh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packet',
            name='rst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packet',
            name='syn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packet',
            name='urg',
            field=models.BooleanField(default=False),
        ),
    ]
