# Generated by Django 3.1.7 on 2021-03-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(default=None)),
                ('scan', models.TextField(default='{}')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
