# Generated by Django 3.1.7 on 2021-04-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packet',
            name='ack',
        ),
        migrations.RemoveField(
            model_name='packet',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='packet',
            name='psh',
        ),
        migrations.RemoveField(
            model_name='packet',
            name='rst',
        ),
        migrations.RemoveField(
            model_name='packet',
            name='syn',
        ),
        migrations.RemoveField(
            model_name='packet',
            name='urg',
        ),
        migrations.AddField(
            model_name='packet',
            name='flags',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='protocol',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
