# Generated by Django 3.1.6 on 2021-02-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0002_auto_20210224_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='payload',
            field=models.TextField(default=''),
        ),
    ]
