# Generated by Django 3.1.6 on 2021-02-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0003_packet_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='dest_ip_address',
            field=models.CharField(default='default', max_length=39),
        ),
        migrations.AlterField(
            model_name='packet',
            name='host_ip_address',
            field=models.CharField(default='default', max_length=39),
        ),
        migrations.AlterField(
            model_name='packet',
            name='port',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
