# Generated by Django 3.1.6 on 2021-02-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0004_auto_20210224_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='dest_ip_address',
            field=models.CharField(default='-1', max_length=39),
        ),
        migrations.AlterField(
            model_name='packet',
            name='host_ip_address',
            field=models.CharField(default='-1', max_length=39),
        ),
        migrations.AlterField(
            model_name='packet',
            name='port',
            field=models.CharField(default='-1', max_length=5),
        ),
    ]
